id: P010507
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20836
  title: གསང་སྔགས་ལམ་གྱི་རིམ་པ་རིན་པོ་ཆེ་གསལ་བའི་སྒྲོན་མེ་དང་གསང་སྔགས་ནང་གི་ལམ་རིམ་རྒྱ་ཆེར་འགྲེལ་པ།
  author: ''
  volumes: {}
