id: P010507
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS20836
  title: གསང་སྔགས་ལམ་གྱི་རིམ་པ་རིན་པོ་ཆེ་གསལ་བའི་སྒྲོན་མེ་དང་གསང་སྔགས་ནང་གི་ལམ་རིམ་རྒྱ་ཆེར་འགྲེལ་པ།
  author: ''
  volumes:
    82ddf78269c94a388495e6a99fc645d5:
      image_group_id: I8LS20838
      title: ''
      volume_number: 1
      total_pages: 704
      base_file: v001.txt
